#配置端口
server:
  port: 8080
#禁用thymeleaf的缓存
spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/drugplatform?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/ygjy/mapper/*.xml
  type-aliases-package: com.ygjy.pojo