#配置端口
server:
  port: 8080
#禁用thymeleaf的缓存
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

  datasource:
    url: jdbc:mysql://localhost:3306/drugplatform?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/ygjy/**/mapper/*.xml
  type-aliases-package: com.ygjy.pojo
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql